#!/bin/sh

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then







    xrdb -merge $sysresources

fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then







    xrdb -merge "$userresources"

fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

# twm &
# xclock -geometry 50x50-1+1 &
# xterm -geometry 80x50+494+51 &
# xterm -geometry 80x20+494-0 &
# exec xterm -geometry 80x66+0+0 -name login

xset +fp /usr/share/fonts/misc # Inform the X server of new directories
xset fp rehash                # Forces a new rescan

# Set wallpaper
feh --bg-scale ~/Pictures/Wallpapers/177.jpg &

# Autostart apps
google-chrome-stable &
volumeicon &
compton &
mpd &

#start notification server
dunst &

#xsetroot -cursor_name left_ptr &
#exec bspwm

/home/lounge/.dwm_clock &

# Run dwm
exec dwm
