#!/bin/sh

battery() {
    BATC=/sys/class/power_supply/BAT0/capacity
    BATS=/sys/class/power_supply/BAT0/status

    test "`cat $BATS`" = "Charging" && echo -n '+' || echo -n '-'

    sed -n p $BATC
}

while :; do
  echo "%{c}$(date '+%a %d %b %H:%M')"
	sleep 2s
done | lemonbar -d -f "$(xrq URxvt*font)" -F "$(xrq *foreground)" -B "$(xrq *background)" -g "120x18+1799+2"
